# train parameters
dataset: 'amazon'
seed: 14
epoch: 1000
early_stop: 50
lr: 0.01
weight_decay: 0.00005
cuda: 0
log: True
data_path: '../data/'
result_path: '../result/'


# model parameters
gamma: 0.4
intra_dim: 8
n_class: 2
head: 4
n_layer: 2
dropout: 0.1

